[theme]
base = "dark"
primaryColor = "#38BDF8"
backgroundColor = "#080B11"
secondaryBackgroundColor = "#111622"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[client]
toolbarMode = "minimal"
showErrorDetails = false
